import type { Order } from "@/lib/contracts/commerce";
import { formatMoney } from "@/lib/format";

/**
 * Receipt download (Task 4 — local commerce). Generates a plain-text receipt
 * from the order row and triggers a browser download. Purely client-side —
 * no server, no external file host.
 */
export function downloadReceipt(order: Order): void {
  if (typeof window === "undefined") return;

  const lines = [
    "ZAPSTERS — PAYMENT RECEIPT",
    "==========================",
    "",
    `Receipt no.    ${order.order_id}`,
    `Order date     ${new Date(order.created_at).toLocaleString()}`,
    `Provider       ${order.provider}`,
    `Status         ${order.status}`,
    `Checkout       ${order.checkout_id}`,
    `Idempotency    ${order.idempotency_key}`,
    "",
    "Items",
    "-----",
    ...order.items.map(
      (item) =>
        `${item.quantity} × ${item.title} (${item.kind}) — ${formatMoney(item.unit_price_cents * item.quantity, order.currency)}`,
    ),
    "",
    `Total          ${formatMoney(order.amount_cents, order.currency)}`,
    "",
    "Thank you for learning with Zapsters.",
    "This is a simulated receipt generated by the frontend demo.",
  ];

  const blob = new Blob([lines.join("\n")], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = `${order.order_id}-receipt.txt`;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(url);
}
