"""init content tables

Revision ID: 6418234aec24
Revises:
Create Date: 2026-08-13 23:28:51.576673

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6418234aec24"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = ("content",)
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "course",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("subtitle", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=80), nullable=False),
        sa.Column("level", sa.String(length=20), nullable=False),
        sa.Column("language", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("submitted_by", sa.UUID(), nullable=True),
        sa.Column("reviewed_by", sa.UUID(), nullable=True),
        sa.Column("instructor_user_id", sa.UUID(), nullable=False),
        sa.Column("price_cents", sa.Integer(), nullable=False),
        sa.Column("estimated_hours", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("format", sa.String(length=20), nullable=True),
        sa.Column("career_track", sa.String(length=40), nullable=True),
        sa.Column("is_project_based", sa.Boolean(), nullable=False),
        sa.Column("certificate_included", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("course_pkey")),
    )
    op.create_table(
        "module",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("course_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"], ["course.id"], name=op.f("module_course_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("module_pkey")),
    )
    op.create_table(
        "lesson",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("module_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("is_preview", sa.Boolean(), nullable=False),
        sa.Column("preview_body", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["module_id"], ["module.id"], name=op.f("lesson_module_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("lesson_pkey")),
    )
    op.create_table(
        "enrollment",
        sa.Column("course_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("progress_pct", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("last_lesson_id", sa.UUID(), nullable=True),
        sa.Column("last_position_seconds", sa.Integer(), nullable=False),
        sa.Column(
            "enrolled_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["course_id"], ["course.id"], name=op.f("enrollment_course_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["last_lesson_id"],
            ["lesson.id"],
            name=op.f("enrollment_last_lesson_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("course_id", "user_id", name=op.f("enrollment_pkey")),
    )
    op.create_table(
        "lesson_progress",
        sa.Column("lesson_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("progress_pct", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("last_position_seconds", sa.Integer(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["lesson_id"],
            ["lesson.id"],
            name=op.f("lesson_progress_lesson_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("lesson_id", "user_id", name=op.f("lesson_progress_pkey")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("lesson_progress")
    op.drop_table("enrollment")
    op.drop_table("lesson")
    op.drop_table("module")
    op.drop_table("course")
    # ### end Alembic commands ###
