"""init labs tables

Revision ID: 0ec1461a7162
Revises:
Create Date: 2026-08-13 23:28:54.311039

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0ec1461a7162"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = ("labs",)
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lab",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=80), nullable=False),
        sa.Column("difficulty", sa.String(length=20), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("estimated_minutes", sa.Integer(), nullable=False),
        sa.Column("requires_gui", sa.Boolean(), nullable=False),
        sa.Column("hard_timeout_minutes", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("lab_pkey")),
        sa.UniqueConstraint("slug", name=op.f("lab_slug_key")),
    )
    op.create_table(
        "lab_objective",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("lab_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("hints", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("requires_terminal", sa.Boolean(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["lab_id"], ["lab.id"], name=op.f("lab_objective_lab_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", "lab_id", name=op.f("lab_objective_pkey")),
    )
    op.create_table(
        "lab_session",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("lab_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "provisioned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("objectives_completed", sa.ARRAY(sa.String(length=80)), nullable=False),
        sa.Column("checks", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("hints_used", sa.Integer(), nullable=False),
        sa.Column("terminal_url", sa.String(length=300), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["lab_id"], ["lab.id"], name=op.f("lab_session_lab_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("session_id", name=op.f("lab_session_pkey")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("lab_session")
    op.drop_table("lab_objective")
    op.drop_table("lab")
    # ### end Alembic commands ###
