"""init gamification tables

Revision ID: da96596d5d79
Revises:
Create Date: 2026-08-13 23:29:57.851205

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "da96596d5d79"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = ("gamification",)
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "progress_context_snapshot",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("context_version", sa.Integer(), nullable=False),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("rank", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("streak", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("league", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("guild", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("unresolved_flags", sa.ARRAY(sa.String(length=60)), nullable=False),
        sa.Column("freeze_status", sa.String(length=30), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("progress_context_snapshot_pkey")),
    )
    op.create_index(
        op.f("progress_context_snapshot_user_id_idx"),
        "progress_context_snapshot",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "xp_ledger",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("xp_type", sa.String(length=20), nullable=False),
        sa.Column("xp_delta", sa.Integer(), nullable=False),
        sa.Column("reason_code", sa.String(length=80), nullable=False),
        sa.Column("multiplier_applied", sa.Float(), nullable=False),
        sa.Column("prev_hash", sa.String(length=64), nullable=False),
        sa.Column("entry_hash", sa.String(length=64), nullable=False),
        sa.Column("integrity_status", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id", "created_at", name=op.f("xp_ledger_pkey")),
    )
    op.create_index(op.f("xp_ledger_user_id_idx"), "xp_ledger", ["user_id"], unique=False)
    # ### end Alembic commands ###

    # xp_ledger is a TimescaleDB hypertable, partitioned by created_at (gamification §2.4,
    # build.md B3) — not autogenerated by SQLAlchemy reflection, added by hand.
    op.execute(
        "SELECT create_hypertable('xp_ledger', 'created_at', if_not_exists => TRUE, "
        "migrate_data => TRUE)"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("xp_ledger_user_id_idx"), table_name="xp_ledger")
    op.drop_table("xp_ledger")
    op.drop_index(
        op.f("progress_context_snapshot_user_id_idx"), table_name="progress_context_snapshot"
    )
    op.drop_table("progress_context_snapshot")
    # ### end Alembic commands ###
