"""init platform_events tables

Revision ID: 4d0e22351499
Revises:
Create Date: 2026-08-13 23:28:50.263619

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4d0e22351499"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = ("platform_events",)
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "processed_event",
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("consumer_group", sa.String(length=80), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column(
            "processed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "idempotency_key", "consumer_group", name=op.f("processed_event_pkey")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("processed_event")
    # ### end Alembic commands ###
